// dashboard-react/src/components/Dashboard.tsx
import { useState, CSSProperties, FC, useEffect } from 'react';
import { DashboardWidget } from './DashboardWidget';
import { DailyWeatherWidget } from './DailyWeatherWidget';
import { RandomColorWidget } from './RandomColorWidget';

interface Widget {
  sortOrder: number,
  component: FC,
}

export const Dashboard = () => {
  const [widgets, setWidgets] = useState<Widget[]>([]);
  useEffect(() => {
    const randomWidgets: Widget[] = makeRandomWidgets();

    // Add a DailyWeatherWidget to the random widgets
    randomWidgets.push({ sortOrder: 5, component: DailyWeatherWidget });
    randomWidgets.sort((a, b) => a.sortOrder - b.sortOrder);

    setWidgets(randomWidgets);
  }, []);
  return (
    <section style={styles.dashboardWrapper}>
      {[...widgets]
        .map((widget: Widget, i: number) => (
          <DashboardWidget key={i}>
            <widget.component />
          </DashboardWidget>
        )
        )
      }
    </section>
  )

  /// Create the array of widgets for the dashboard
  function makeRandomWidgets(numberOfWidgets = 25): Widget[] {
    return [...Array(numberOfWidgets)].map<Widget>((_, i) => ({
      sortOrder: i,
      component: RandomColorWidget,
    }));
  }
}
const styles: { [Name: string]: CSSProperties } = {
  dashboardWrapper: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
  }
}

// dashboard-svelte/src/components/Dashboard.svelte
<script lang="ts">
  //TODO: Try to put types in this like in the React project (a Widget for example)
  import DailyWeatherWidget from "./DailyWeatherWidget.svelte";
  import RandomColorWidget from "./RandomColorWidget.svelte";

  import DashboardWidget from "./DashboardWidget.svelte";

  const widgets = makeRandomWidgets().sort((a, b) => a.sortOrder - b.sortOrder);
  // Add a DailyWeatherWidget to the random widgets
  widgets.push({ sortOrder: 3, component: DailyWeatherWidget });
  widgets.sort((a, b) => a.sortOrder - b.sortOrder);

  /// Create the array of widgets for the dashboard
  function makeRandomWidgets(numberOfWidgets = 25) {
    return [...Array(numberOfWidgets)].map((_, i) => ({
      sortOrder: i,
      component: RandomColorWidget,
    }));
  }
</script>

<section id="dashboardWrapper">
  {#each widgets as widget}
    <DashboardWidget>
      <svelte:component this={widget.component} />
    </DashboardWidget>
  {/each}
</section>

<style>
  #dashboardWrapper {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
  }
</style>
