// dashboard-react/src/components/DailyWeatherWidget.tsx
import { useEffect, useState, FC, CSSProperties } from 'react';
import { Forecast } from '../types/Forecast';
import { ForecastFC } from './Forecast';

export const DailyWeatherWidget: FC = () => {
  const [forecasts, setForecasts] = useState<Forecast[]>([])
  useEffect(() => {
    (async function () {
      const url = `https://api.open-meteo.com/v1/forecast?latitude=32.98&longitude=-96.68&daily=weathercode&timezone=UTC`;
      const daily = await fetch(url)
        .then<ForecastResponse>(res => res.json())
        .then(res => res.daily)
      setForecasts(daily.time.slice(0, 5).map((time, i) => ({ time, weatherCode: daily.weathercode[i] })))
    })()
  }, []);
  console.log("forecasts", forecasts)
  return (
    <section style={styles.widgetWrapper}>
      <h1 style={styles.title}>5 day weather forecast</h1>
      <section style={styles.daysWrapper}>
        {forecasts.map((forecast: Forecast) => <ForecastFC forecast={forecast} key={forecast.time} />)}
      </section>
    </section>
  )
}


const styles: { [Name: string]: CSSProperties } = {
  title: {
    fontSize: 24,
    textTransform: 'uppercase',
  },
  widgetWrapper: {
    textAlign: "center",
    height: '100%',
  },
  daysWrapper: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, minmax(0, 1fr))',
  },
}


interface ForecastResponse {
  daily: {
    time: string[],
    weathercode: number[],
  },
}

// dashboard-angular/src/app/components/daily-weather-widget/daily-weather-widget.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Forecast } from 'src/app/types/Forecast';

@Component({
  selector: 'app-daily-weather-widget',
  templateUrl: './daily-weather-widget.component.html',
  styleUrls: ['./daily-weather-widget.component.css']
})
export class DailyWeatherWidgetComponent implements OnInit {
  forecasts: Forecast[] = [];
  constructor(private _http: HttpClient) { }

  ngOnInit(): void {
    const url = `https://api.open-meteo.com/v1/forecast?latitude=32.98&longitude=-96.68&daily=weathercode&timezone=UTC`;
    this._http.get<ForecastResponse>(url)
      .subscribe((res: ForecastResponse) => {
        const daily = res.daily;
        this.forecasts = daily.time.slice(0, 5).map((time: any, i: number) => ({ time, weatherCode: daily.weathercode[i] }));
      })
  }
}

interface ForecastResponse {
  daily: {
    time: string[],
    weathercode: number[],
  },
}

<section id="widgetWrapper">
  <h1 id="title">5 day weather forecast</h1>
  <section id="daysWrapper">
    <forecast *ngFor="let forecast of forecasts" [forecast]="forecast"></forecast>
  </section>
</section>
