// dashboard-svelte/src/components/RandomColorWidget.svelte
<script lang="ts">
  const backgroundColor =
    "#" + Math.floor(Math.random() * 0xffffff).toString(16);
  const color = `color-contrast(${backgroundColor} vs black, white)`; // This'll be cool once its supported by all browsers.
</script>

<div id="wrapper" style="background-color: {backgroundColor}; color: {color}">
  Placeholder widget
</div>

<style>
  #wrapper {
    background-color: yellow;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 1.5em;
  }
</style>

// dashboard-angular/src/app/components/random-color-widget/random-color-widget.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: `random-color-widget`,
  template: `
    <div [ngStyle]="{backgroundColor:backgroundColor, color: color}">
      Placeholder widget
    </div>
  `,
  styles: [`
    div {
      background-color: yellow;
      height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
      font-size: 1.5em;
     }
  `],
})
export class RandomColorWidgetComponent implements OnInit {
  backgroundColor: String = "";
  color: String = "";
  ngOnInit() {
    this.backgroundColor = '#' + Math.floor(Math.random() * 0xffffff).toString(16);
    this.color = `color-contrast(${this.backgroundColor} vs black, white)`; // This'll be cool once its supported by all browsers.
  }
}
