// dashboard-angular/src/app/components/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { DailyWeatherWidgetComponent } from '../daily-weather-widget/daily-weather-widget.component';
import { RandomColorWidgetComponent } from '../random-color-widget/random-color-widget.component';

interface Widget {
  sortOrder: number,
  component: any,  // This is a real weakness of Angular
}

@Component({
  selector: 'dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  widgets: Widget[] = [];
  constructor() { }

  ngOnInit(): void {
    const randomWidgets: Widget[] = this.makeRandomWidgets();

    // Add a DailyWeatherWidget to the random widgets
    randomWidgets.push({ sortOrder: 3, component: DailyWeatherWidgetComponent });
    randomWidgets.sort((a, b) => a.sortOrder - b.sortOrder);
    this.widgets = randomWidgets;
  }

  /// Create the array of widgets for the dashboard
  makeRandomWidgets(numberOfWidgets = 25): Widget[] {
    return [...Array(numberOfWidgets)].map<Widget>((_, i) => ({
      sortOrder: i,
      component: RandomColorWidgetComponent,
    }))
  }
}

<section id="dashboardWrapper">
  <dashboard-widget *ngFor="let widget of widgets" [child]="widget.component" class="dashboardWidget">
  </dashboard-widget>
</section>

// dashboard-react/src/components/Dashboard.tsx
import { useState, CSSProperties, FC, useEffect } from 'react';
import { DashboardWidget } from './DashboardWidget';
import { DailyWeatherWidget } from './DailyWeatherWidget';
import { RandomColorWidget } from './RandomColorWidget';

interface Widget {
  sortOrder: number,
  component: FC,
}

export const Dashboard = () => {
  const [widgets, setWidgets] = useState<Widget[]>([]);
  useEffect(() => {
    const randomWidgets: Widget[] = makeRandomWidgets();

    // Add a DailyWeatherWidget to the random widgets
    randomWidgets.push({ sortOrder: 5, component: DailyWeatherWidget });
    randomWidgets.sort((a, b) => a.sortOrder - b.sortOrder);

    setWidgets(randomWidgets);
  }, []);
  return (
    <section style={styles.dashboardWrapper}>
      {[...widgets]
        .map((widget: Widget, i: number) => (
          <DashboardWidget key={i}>
            <widget.component />
          </DashboardWidget>
        )
        )
      }
    </section>
  )

  /// Create the array of widgets for the dashboard
  function makeRandomWidgets(numberOfWidgets = 25): Widget[] {
    return [...Array(numberOfWidgets)].map<Widget>((_, i) => ({
      sortOrder: i,
      component: RandomColorWidget,
    }));
  }
}
const styles: { [Name: string]: CSSProperties } = {
  dashboardWrapper: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
  }
}
